### ISSUE TITLE
Docker arguments are ignored when starting the diuid container

### ISSUE THREAD

**Issue by b1zzu** [weber-software/diuid#20]
If I try to start the diuid container all args I pass are completely ignored, for example, if I execute this:

```
docker run -it weberlars/diuid sh
```

the container will just exit after `waiting for dockerd ....` and the bash is never executed

**Comment by b1zzu** [comment]
After some tentative, I found out that removing the code from line 28 to 38 of the entrypoint.sh fix the problem
https://github.com/weber-software/diuid/blob/84466f0491bcf7c2460c6fb863bac855351df436/entrypoint.sh#L28

**Comment by weber-software** [comment]
are you passing any flags in `DIUID_DOCKERD_FLAGS`?

**Comment by b1zzu** [comment]
No, I'm not passing any flags

**Comment by AkihiroSuda** [comment]
Fixed in https://github.com/weber-software/diuid/pull/21
