### ISSUE TITLE
Request: enable CI (travis?)

### ISSUE THREAD

**Issue by AkihiroSuda** [weber-software/diuid#9]

**Comment by weber-software** [comment]
For testing purpose? The build is already done by docker-hub.

**Comment by AkihiroSuda** [comment]
Yes, I'm thinking of adding some smoke test scripts like this
```
#!/bin/sh
set -exu

docker build -t diuid .
docker run --rm diuid docker run hello-world
# tests for `docker run -p` will be added later when implemented
```

**Comment by weber-software** [comment]
I enabled Travis-CI for the project. But i have never used it before. If you have a MR with a starting point that would be great.

**Comment by AkihiroSuda** [comment]
sure #11

**Comment by weber-software** [comment]
many thanks
